// Headless logic checks for Gabriel's Animation Studio.
// Run: node test/run.js   (needs Node 18+; no packages)
const fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(process.env.GAS_ROOT||path.join(__dirname,'..'),'index.html'),'utf8');
let script=html.match(/<script>([\s\S]*)<\/script>/)[1];
const HOOK=`window.__t={get strokes(){return strokes},setStrokes(l){strokes=l;nextId=Math.max(0,...l.map(s=>s.id))+1;rig=null;history=[];dirty=true;},get rig(){return rig},get game(){return game},get outfit(){return outfit},setOutfit(o){outfit=o;},get morph(){return morph},setMorph,get morphT(){return morphT},startAnimation,stopAnimation,startGame,startModGame,backToDrawing,jump,held,inputDown,inputUp,inp,FIGHT,BRAWL,QUEST,HOUSE,PLANE,HOOPS,BOTS,OUTFIT_SLOTS,perksFor,validOutfit,LB,LB_GAMES,get player(){return player},setPlayerName,cleanName,openLeaderboard,openNameModal,lbReport,lbFlush,lbTop,localBest,get lbQueue(){return lbQueue},get lbCache(){return lbCache},get lbLocal(){return lbLocal},lbUid,lbAuth,get lbAuthState(){return lbAuthState},setAuthState(v){lbAuthState=v;},setFetch(f){window.fetch=f;},setOnline(v){window.navigator={onLine:v};},makeBot,botStrokes,snapshotHero,loadHero,get heroes(){return heroes},buildCharacter,currentCharacter,drawCharacterThumb,serializeChar,validChar,scene,SCENES,setBackground(i){background=i;},get background(){return background},openScenePicker,openHeroes,openVsSetup,openQuestMap,openOnline,closeModal,storageSave,load,get progress(){return progress},genLevel,WORLDS,ensureRig,netGuestUpdate,NET,finishMod,poseFor,fightOptions,get animation(){return animation},get heroName(){return heroName},get audio(){return audio},unlockAudio,musicTick,MUSIC,get musicMode(){return musicMode},setMusicMode(m){musicMode=m;},musicApply,musicPause,openMusic,songSet,songPlay,GROOVE,noteHz};`;
if(!script.includes('/* TEST_HOOK */'))throw new Error('TEST_HOOK marker missing');
script=script.replace('/* TEST_HOOK */',HOOK);
// ---- fake DOM ----
function makeCtx(){const t={globalAlpha:1,lineWidth:1,font:'',textAlign:'',textBaseline:'',fillStyle:'',strokeStyle:'',lineCap:'',lineJoin:''};return new Proxy(t,{get(o,k){if(k in o)return o[k];if(k==='createLinearGradient'||k==='createRadialGradient')return()=>({addColorStop(){}});if(k==='measureText')return()=>({width:10});if(k==='getImageData')return()=>({data:new Uint8ClampedArray(4)});return()=>undefined;},set(o,k,v){o[k]=v;return true;}});}
class El{constructor(tag,id){this.tag=tag;this.id=id||'';this.textContent='';this.hidden=false;this.disabled=false;this.className='';this.children=[];this.attrs={};this.dataset={};this.style={setProperty(){}};this.value='';this.width=300;this.height=150;const cls=new Set();this.classList={add:c=>cls.add(c),remove:c=>cls.delete(c),toggle:(c,f)=>{f===undefined?(cls.has(c)?cls.delete(c):cls.add(c)):(f?cls.add(c):cls.delete(c));},contains:c=>cls.has(c)};this._ctx=null;}
getContext(){return this._ctx||(this._ctx=makeCtx());}
setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k];}append(...n){this.children.push(...n);}
set innerHTML(v){this.children=[];}get innerHTML(){return '';}
querySelectorAll(sel){const out=[];const walk=n=>{for(const c of n.children||[]){if(!(c instanceof El))continue;if(sel==='button'&&c.tag==='button')out.push(c);walk(c);}};walk(this);return out;}
addEventListener(){}removeEventListener(){}focus(){}
getBoundingClientRect(){return{left:0,top:0,width:1280,height:720};}
setPointerCapture(){}releasePointerCapture(){}hasPointerCapture(){return false;}}
const byId=new Map();
const doc={hidden:false,body:new El('body'),head:new El('head'),modelContext:undefined,getElementById(id){if(!byId.has(id))byId.set(id,new El('div',id));return byId.get(id);},createElement(tag){return new El(tag);},querySelectorAll(){return[];},addEventListener(){},removeEventListener(){}};
byId.set('canvas',Object.assign(new El('canvas','canvas'),{width:1280,height:720}));
function anode(){const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},linearRampToValueAtTime(){}});return{connect(){},disconnect(){},start(){},stop(){},type:'',frequency:param(),gain:param(),Q:param(),buffer:null,loop:false};}
class FakeAudioContext{constructor(){this.state='running';this.currentTime=0;this.sampleRate=44100;this.destination={};}createOscillator(){return anode();}createGain(){return anode();}createBiquadFilter(){return anode();}createBufferSource(){return anode();}createBuffer(c,l){return{getChannelData(){return new Float32Array(l);}};}resume(){return Promise.resolve();}}
const store=new Map();const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
let rafCb=null;
const win={document:doc,localStorage,AudioContext:FakeAudioContext,setInterval,clearInterval,URL:{createObjectURL:()=>'blob:fake',revokeObjectURL(){}},addEventListener(){},devicePixelRatio:1,requestAnimationFrame(cb){rafCb=cb;return 1;},setTimeout,clearTimeout,Date,Math,JSON,Number,String,Array,Object,Set,Map,Promise,Error,Uint8ClampedArray,console,performance:{now:()=>Date.now()},AbortController:class{constructor(){this.signal={}}abort(){}},isFinite,parseInt,parseFloat};
win.window=win;win.self=win;
function boot(){if(win.__t&&win.__t.musicPause)try{win.__t.musicPause();}catch(e){}byId.clear();byId.set('canvas',Object.assign(new El('canvas','canvas'),{width:1280,height:720}));rafCb=null;const ctx=vm.createContext(win);vm.runInContext(script,ctx,{filename:'index.html'});return win.__t;}
let now=0;function step(n=1){for(let i=0;i<n;i++){now+=16.67;if(win.__t&&win.__t.audio)win.__t.audio.currentTime+=1/60;const cb=rafCb;rafCb=null;cb(now);if(!rafCb)throw new Error('frame did not re-register');}}
let passed=0,failed=0;const fails=[];
const TESTS=[];function check(name,fn){TESTS.push([name,fn]);}
async function runChecks(){for(const [name,fn] of TESTS){try{await fn();passed++;console.log('  ok   '+name);}catch(e){failed++;fails.push(name+': '+(e&&e.stack||e));console.log('  FAIL '+name+' -> '+(e&&e.message||e));}}}
function assert(c,msg){if(!c)throw new Error(msg||'assertion failed');}
// ---- tests ----
if(require.main!==module){module.exports={boot,step,byId,doc,store,check,assert};return;}
console.log('Booting game script...');
let t=boot();
const stick=(color='#e65345')=>t.botStrokes(color).map(s=>({...s,points:s.points.map(p=>({...p}))}));
check('boots and renders 5 frames',()=>{step(5);assert(t.game===null);});
check('rig inferred from a stick figure and Walk animates',()=>{t.setStrokes(stick());assert(t.startAnimation('Walk'));assert(t.rig,'rig missing');assert(t.rig.fit.scale>0);step(40);assert(t.animation==='Walk');t.stopAnimation();});
check('every movement animates',()=>{for(const m of ['Walk','Run','Jump','Dance','Wave','Kick','Flip','Cartwheel','Fly','Zombie']){assert(t.startAnimation(m));step(10);t.stopAnimation();}});
check('fight poses resolve for every fit',()=>{for(const n of ['Guard','Punch','Swing','Shoot','Block','Hurt','KO','Win','Fall','Sit']){const p=t.poseFor(n,.3,t.rig.fit);assert(p&&typeof p==='object');for(const k in p)assert(Number.isFinite(p[k]),n+'.'+k+' not finite');}});
check('outfits and morph paint without errors',()=>{for(const hat of ['','crown','wizard','cap','helmet','halo','party','horns'])for(const weapon of ['','sword','axe','hammer','wand','blaster','bow','shield']){t.setOutfit({hat,cape:['','red','rainbow','shadow'][hat.length%4],top:['','shirt','armor','super','robe','ninja','stripes'][weapon.length%7],weapon});t.startAnimation('Run');step(3);t.stopAnimation();}t.setMorph(true);step(80);assert(t.morphT===1,'morphT '+t.morphT);t.startAnimation('Dance');step(20);t.stopAnimation();t.setMorph(false);step(80);assert(t.morphT===0);});
check('all 18 scenes draw (normal and thumbnails)',()=>{for(let i=0;i<t.SCENES.length;i++){t.setBackground(i);t.scene(1.5,300);}t.openScenePicker();t.closeModal();t.setBackground(6);});
check('legacy games run with outfits on',()=>{t.setOutfit({hat:'crown',cape:'red',top:'super',weapon:'sword'});t.setMorph(true);for(const type of ['platform','dash','catch','flap','pop','dodge','bounce','goal']){assert(t.startGame(type),type);for(let i=0;i<240;i++){if(i%40===0)t.held.right.add('k');if(i%40===25)t.held.right.delete('k');if(i%30===0)t.jump();step(1);}t.backToDrawing();}});
check('hero library: save, build, thumbnail, load',()=>{const h=t.snapshotHero('Test Hero');assert(h&&h.name==='Test Hero');assert(t.heroes.length===1);const ch=t.buildCharacter(h);assert(ch.rig.bindings.size===h.strokes.length);const c=doc.createElement('canvas');c.width=c.height=140;t.drawCharacterThumb(c,ch);t.loadHero(h);assert(t.rig&&t.heroName==='Test Hero');t.openHeroes();t.closeModal();});
check('all four bots build',()=>{for(const b of t.BOTS){const ch=t.makeBot(b);assert(ch.rig.fit.headR>10,b.name+' head');assert(ch.rest.h>200,b.name+' height');}});
check('online hero payload round-trips',()=>{const me=t.currentCharacter();const s=JSON.parse(JSON.stringify(t.serializeChar(me)));assert(t.validChar(s));const back=t.buildCharacter(s);assert(back.strokes.length===s.strokes.length);});
function randomInputs(pl,i){const acts=['left','right','up','a','b','c'];if(i%7===0){for(const a of acts)t.inputUp(pl,a,'t');t.inputDown(pl,acts[(i/7|0)%acts.length],'t');}}
check('VS Computer fight finishes with a result (hard bot, weapons)',()=>{const me=t.currentCharacter();const bot=t.makeBot(t.BOTS[0]);assert(t.startModGame(t.FIGHT,{p1:me,p2:bot,cpu:'hard'}));let i=0;while(!t.game.over&&i<60*200){randomInputs('p1',i);step(1);i++;}assert(t.game.over,'fight never ended');assert(byId.get('resultTitle').textContent.length>0);t.backToDrawing();});
check('2-player fight, all bots, finishes',()=>{const a=t.makeBot(t.BOTS[1]),b=t.makeBot(t.BOTS[3]);assert(t.startModGame(t.FIGHT,{p1:a,p2:b}));assert(t.game.duo===true);let i=0;while(!t.game.over&&i<60*200){randomInputs('p1',i);randomInputs('p2',i+3);step(1);i++;}assert(t.game.over,'2p fight never ended');t.backToDrawing();});
check('round timer runs out gives a decision',()=>{const a=t.makeBot(t.BOTS[2]),b=t.makeBot(t.BOTS[2]);t.startModGame(t.FIGHT,{p1:a,p2:b});let i=0;while(!t.game.over&&i<60*230){step(1);i++;}assert(t.game.over,'idle fight never ended');t.backToDrawing();});
check('Monster Brawl: a scripted player beats wave 1 slimes by punching',()=>{assert(t.startModGame(t.BRAWL,{}));let i=0;while(!t.game.over&&i<60*60){const A=t.game.arena,f=A.player,e=A.enemies[0];if(A.wave>=2)break;if(e){const d=e.x-f.x;t.inputUp('p1','left','k');t.inputUp('p1','right','k');if(Math.abs(d)>90)t.inputDown('p1',d>0?'right':'left','k');else if(i%20===0)t.inputDown('p1','a','k');else t.inputUp('p1','a','k');}step(1);i++;}assert(t.game.arena.kills>=3,'kills '+t.game.arena.kills+' hp '+t.game.arena.player.hp);t.backToDrawing();});
check('Monster Brawl: all waves and the boss can be won',()=>{assert(t.startModGame(t.BRAWL,{}));let i=0,waves=new Set();while(!t.game.over&&i<60*120){const A=t.game.arena;waves.add(A.wave);A.player.hp=100;if(i%60===0)A.enemies.forEach(e=>{e.hp=0;});step(1);i++;}assert(t.game.over&&/Champion/.test(byId.get('resultTitle').textContent),'waves '+[...waves]+' title '+byId.get('resultTitle').textContent);t.backToDrawing();});
check('Monster Brawl loss path',()=>{t.startModGame(t.BRAWL,{});t.game.arena.player.hp=1;let i=0;while(!t.game.over&&i<60*60){step(1);i++;}assert(t.game.over);assert(/wave/i.test(byId.get('resultText').textContent));t.backToDrawing();});
check('Space Quest: every world generates and runs',()=>{for(let w=0;w<t.WORLDS.length;w++){const L=t.genLevel(t.WORLDS[w]);assert(L.cells.length===5&&L.segs.length>0,'world '+w);assert(t.startModGame(t.QUEST,{world:w}));for(let i=0;i<400&&!t.game.over;i++){randomInputs('p1',i);step(1);}t.backToDrawing();}});
check('Space Quest: chain Earth to the Sun by reaching each rocket',()=>{t.progress.quest.unlocked=1;assert(t.startModGame(t.QUEST,{world:0}));let guard=0;while(!t.game.over&&guard<60*60*5){const q=t.game.q;if(q.phase==='play'){q.p.x=q.level.goal;q.p.y=640;}step(1);guard++;}assert(t.game.over,'never finished');assert(/Sun/.test(byId.get('resultTitle').textContent),byId.get('resultTitle').textContent);assert(t.progress.quest.unlocked===t.WORLDS.length,'unlocked '+t.progress.quest.unlocked);t.openQuestMap();t.closeModal();t.backToDrawing();});
check('Space Quest: falling into pits three times ends the level',()=>{t.startModGame(t.QUEST,{world:2});const q=t.game.q;q.level.segs=[];q.level.plats=[];let i=0;while(!t.game.over&&i<60*30){q.p.inv=0;step(1);i++;}assert(t.game.over,'hearts '+t.game.hearts);assert(/try/i.test(byId.get('resultTitle').textContent));t.backToDrawing();});
check('House Hunt: walk every room and find all 8 things',()=>{assert(t.startModGame(t.HOUSE,{}));const h=t.game.h;const visited=new Set();const go=(room,x)=>{h.room=room;h.p.x=x;};const items=[['living',600],['kitchen',560],['bedroom',520],['bathroom',380],['yard',1000],['garage',980],['basement',1000],['playroom',700]];for(const [room,x] of items){go(room,x);visited.add(room);step(2);}assert(t.game.over,'not finished, found '+h.found.size);assert(/found everything/i.test(byId.get('resultTitle').textContent));t.backToDrawing();
t.startModGame(t.HOUSE,{});const H2=t.game.h;H2.p.x=20;t.inputDown('p1','left','k');step(2);assert(H2.room==='garage','door left -> '+H2.room);t.inputUp('p1','left','k');H2.p.x=1270;t.inputDown('p1','right','k');step(3);assert(H2.room==='living','door right -> '+H2.room);t.inputUp('p1','right','k');H2.p.x=1090;t.inputDown('p1','up','k');step(1);t.inputUp('p1','up','k');assert(H2.room==='bedroom','stairs up -> '+H2.room);t.inputDown('p1','down','k');step(1);t.inputUp('p1','down','k');assert(H2.room==='living','stairs down -> '+H2.room);t.backToDrawing();});
check('save + reload keeps outfit, morph, heroes and progress',()=>{t.setOutfit({hat:'halo',cape:'gold',top:'ninja',weapon:'bow'});t.setMorph(true);t.storageSave();const saved=JSON.parse(store.get('doodle-go-v1'));assert(saved.outfit.hat==='halo'&&saved.morph===true);t=boot();step(2);assert(t.outfit.hat==='halo'&&t.outfit.weapon==='bow',JSON.stringify(t.outfit));assert(t.morph===true&&t.morphT===1);assert(t.heroes.length===1);assert(t.progress.quest.unlocked===t.WORLDS.length);assert(t.rig,'rig restored');});
check('VS setup modal builds with current drawing, heroes and bots',()=>{const opts=t.fightOptions();assert(opts.length===1+1+t.BOTS.length,'options '+opts.length);t.openVsSetup(true);t.closeModal();t.openVsSetup(false);t.closeModal();t.openOnline();t.closeModal();});
check('guest fight applies host snapshots',()=>{const me=t.currentCharacter(),bot=t.makeBot(t.BOTS[2]);t.startModGame(t.FIGHT,{p1:bot,p2:me,online:{role:'guest'}});t.NET.role='guest';t.NET.state={t:'st',ph:'fight',pt:1,rd:1,tm:50,f:[{x:400,y:640,vx:0,vy:0,fc:1,st:'punch',t:.1,hp:80,w:0,g:true,an:1},{x:700,y:640,vx:0,vy:0,fc:-1,st:'hurt',t:.1,hp:60,w:1,g:true,an:1}],sh:[{x:500,y:500,vx:600,type:'wand'}],ev:[{k:'hit',x:600,y:500}]};step(3);const A=t.game.arena;assert(A.fighters[0].hp===80&&A.fighters[1].hp===60&&A.phase==='fight');t.NET.role=null;t.backToDrawing();});
check('music: Elevator Groove schedules notes for a full loop after the first tap',()=>{t.unlockAudio();assert(t.audio,'no audio context');assert(t.MUSIC.running,'groove not running');const before=t.MUSIC.notes;for(let i=0;i<60*20;i++){step(1);t.musicTick();}assert(t.MUSIC.notes-before>400,'notes scheduled '+(t.MUSIC.notes-before));assert(t.MUSIC.step>=0&&t.MUSIC.step<t.GROOVE.bars*16);assert(Math.abs(t.noteHz('A4')-440)<1e-6&&Math.abs(t.noteHz('C#3')-138.59)<.01);t.musicPause();assert(!t.MUSIC.running);});
check('music: modes, song element, modal and persistence',()=>{t.openMusic();t.closeModal();t.setMusicMode('off');t.musicApply();assert(!t.MUSIC.running);t.songSet({name:'test.wav',type:'audio/wav',blob:{}});assert(t.MUSIC.songUrl==='blob:fake'&&t.MUSIC.songName==='test.wav');t.setMusicMode('song');t.musicApply();t.songPlay();t.openMusic();t.closeModal();t.storageSave();const saved=JSON.parse(store.get('doodle-go-v1'));assert(saved.musicMode==='song'&&saved.musicVol===1,JSON.stringify([saved.musicMode,saved.musicVol]));t=boot();step(2);assert(t.musicMode==='song','reloaded mode '+t.musicMode);assert(byId.get('music').textContent==='🎵 My song',byId.get('music').textContent);t.setMusicMode('groove');t.musicApply();assert(t.MUSIC.running,'groove restart');t.musicPause();});
check('Endless Dash: landing on an alien squishes it and scores (Mario stomp)',()=>{assert(t.startGame('dash'));const g=t.game;step(2);const e=g.enemies[0];assert(e,'no alien');g.x=e.x;g.y=e.y-120;g.vy=300;g.grounded=false;const stars=g.stars,hearts=g.hearts;let i=0;while(e.squish===undefined&&i<40){step(1);i++;}assert(e.squish!==undefined,'alien not squished after '+i+' frames (y '+g.y+')');assert(g.stars>=stars+1,'no star for the stomp');assert(g.hearts===hearts,'stomp cost a heart');assert(g.vy<0,'no bounce');step(50);assert(!g.enemies.includes(e),'squished alien still there');t.backToDrawing();});
check('Endless Dash: walking into an alien still hurts',()=>{assert(t.startGame('dash'));const g=t.game;step(2);const e=g.enemies[0];g.x=e.x-40;g.y=640;g.vy=0;g.invulnerable=0;const hearts=g.hearts;step(3);assert(g.hearts===hearts-1,'side hit did not hurt: '+g.hearts);assert(e.squish===undefined,'side hit squished it');t.backToDrawing();});
check('hat brim flip: saved, reloaded and kept on heroes',()=>{t.setOutfit({hat:'cap',cape:'',top:'',weapon:'axe',flip:true});t.startAnimation('Walk');step(3);t.stopAnimation();t.storageSave();const saved=JSON.parse(store.get('doodle-go-v1'));assert(saved.outfit.flip===true,'flip not saved');const h=t.snapshotHero('Brim Hero');assert(h.outfit.flip===true,'flip not on hero');t=boot();step(2);assert(t.outfit.flip===true&&t.outfit.hat==='cap','flip lost on reload '+JSON.stringify(t.outfit));assert(byId.get('brim').textContent.indexOf('left')>0,'brim button text '+byId.get('brim').textContent);t.setOutfit({hat:'crown',cape:'red',top:'super',weapon:'sword',flip:false});});
check('Monster Brawl: hero turns toward the nearest monster without pressing anything',()=>{assert(t.startModGame(t.BRAWL,{}));const A=t.game.arena,f=A.player;step(90);A.enemies.forEach(e=>{e.x=f.x+300;e.state='walk';e.speed=0;});step(2);assert(f.facing===1,'should face right, facing '+f.facing);A.enemies.forEach(e=>{e.x=f.x-300;});step(2);assert(f.facing===-1,'should face left, facing '+f.facing);t.backToDrawing();});
check('fighters: a punch tapped during hitstop is not lost',()=>{assert(t.startModGame(t.BRAWL,{}));const A=t.game.arena,f=A.player;step(90);A.enemies.forEach(e=>{e.x=f.x+400;e.speed=0;});A.hitstop=.2;t.inputDown('p1','a','k');step(1);t.inputUp('p1','a','k');step(1);assert(f.state!=='punch','punched during hitstop?');step(14);assert(f.state==='punch','buffered punch did not fire, state '+f.state+' buf '+JSON.stringify(f.buf));t.backToDrawing();});
check('Sky Pilot: fly through 15 rings, land, win',()=>{assert(t.startModGame(t.PLANE,{}));const g=t.game,F=g.f;let i=0;while(!g.over&&i<60*120){if(F.phase==='fly'){F.objs.length=0;const r=F.rings.find(r=>!r.done&&!r.miss&&r.x>F.dist+F.p.x-20);if(r){F.p.y=r.y;}if(i%50===0)t.inputDown('p1','a','k');else t.inputUp('p1','a','k');}step(1);i++;}assert(g.over&&/Ace/.test(byId.get('resultTitle').textContent),'title '+byId.get('resultTitle').textContent+' got '+F.got);assert(t.progress.bests.plane>=150,'best '+t.progress.bests.plane);t.backToDrawing();});
check('Sky Pilot: storms cost hearts and end the flight',()=>{assert(t.startModGame(t.PLANE,{}));const g=t.game,F=g.f;let i=0;while(!g.over&&i<60*60){F.p.inv=0;F.objs.length=0;F.objs.push({kind:'storm',x:F.dist+F.p.x,y:F.p.y,vx:0,vy:0,r:80,t0:0,dead:false});step(1);i++;}assert(g.over&&/Rough/.test(byId.get('resultTitle').textContent),'title '+byId.get('resultTitle').textContent);t.backToDrawing();});
check('Sky Pilot: random flying runs clean',()=>{assert(t.startModGame(t.PLANE,{}));for(let i=0;i<600&&!t.game.over;i++){randomInputs('p1',i);if(i%37===0)t.jump();step(1);}t.backToDrawing();});
check('Hoop Shot: a green-zone shot from the 3-point line scores 3',()=>{assert(t.startModGame(t.HOOPS,{}));const g=t.game,B=g.b;B.p.x=300;t.inputDown('p1','a','k');step(1);assert(B.charging,'not charging');B.charge=.55;t.inputUp('p1','a','k');step(1);assert(B.ball.st==='air','ball not shot: '+B.ball.st);let i=0;while(B.ball.st==='air'&&i<400){step(1);i++;}assert(B.score===3,'score '+B.score+' made '+B.made+' ball '+JSON.stringify(B.ball));step(150);assert(B.ball.st==='held','ball did not come back: '+B.ball.st);t.backToDrawing();});
check('Hoop Shot: close shot scores 2 and the buzzer ends the game',()=>{assert(t.startModGame(t.HOOPS,{}));const g=t.game,B=g.b;B.p.x=900;t.inputDown('p1','a','k');step(1);B.charge=.55;t.inputUp('p1','a','k');step(1);assert(B.ball.st==='air','not shot');let i=0;while(B.ball.st==='air'&&i<400){step(1);i++;}assert(B.score===2,'score '+B.score);B.timer=.1;step(10);assert(g.over&&/Buzzer/.test(byId.get('resultTitle').textContent),byId.get('resultTitle').textContent);assert(t.progress.bests.hoops===2,'best '+t.progress.bests.hoops);t.backToDrawing();});
check('Hoop Shot: a bad shot misses and random play runs clean',()=>{assert(t.startModGame(t.HOOPS,{}));const B=t.game.b;B.p.x=300;t.inputDown('p1','a','k');step(1);B.charge=0;B.meter=0;t.inputUp('p1','a','k');let i=0;while(B.ball.st==='air'&&i<400){step(1);i++;}assert(B.score===0,'weak shot scored');for(let j=0;j<500&&!t.game.over;j++){randomInputs('p1',j);step(1);}t.backToDrawing();});
check('upgrade pack: every hat, cape, top, weapon and skin paints, morphed and not',()=>{const all=k=>t.OUTFIT_SLOTS[k].map(v=>v[0]);for(const m of [true,false]){t.setMorph(m);step(80);const n=Math.max(all('hat').length,all('cape').length,all('top').length,all('weapon').length,all('skin').length);for(let i=0;i<n;i++){t.setOutfit({hat:all('hat')[i%all('hat').length],cape:all('cape')[i%all('cape').length],top:all('top')[i%all('top').length],weapon:all('weapon')[i%all('weapon').length],skin:all('skin')[i%all('skin').length],flip:i%2===0});t.startAnimation('Run');step(3);t.stopAnimation();}}t.setOutfit({hat:'crown',cape:'red',top:'super',weapon:'sword',skin:'',flip:false});t.setMorph(true);step(80);});
check('upgrade pack: new weapons have perks and the bazooka shoots',()=>{for(const w of ['laser','katana','trident','scythe'])assert(t.perksFor({outfit:{weapon:w}}).melee===w,w);const pk=t.perksFor({outfit:{weapon:'bazooka'}});assert(pk.shoot==='bazooka');const me=t.currentCharacter(),bot=t.makeBot(t.BOTS.find(b=>b.name==='Astro Ace'));assert(t.startModGame(t.FIGHT,{p1:me,p2:bot,cpu:'hard'}));let i=0,shot=false;while(!t.game.over&&i<60*60){randomInputs('p1',i);step(1);i++;if(t.game.arena.shots.some(s=>s.type==='bazooka'))shot=true;}assert(shot,'bazooka never fired');t.backToDrawing();});
check('upgrade pack: Lava Lord and Astro Ace fight each other to a result',()=>{const a=t.makeBot(t.BOTS[4]),b=t.makeBot(t.BOTS[5]);assert(t.startModGame(t.FIGHT,{p1:a,p2:b}));let i=0;while(!t.game.over&&i<60*200){randomInputs('p1',i);randomInputs('p2',i+3);step(1);i++;}assert(t.game.over);t.backToDrawing();});
check('skins: picking a skin saves and survives reload',()=>{t.setOutfit({hat:'',cape:'',top:'',weapon:'',skin:'alien',flip:false});t.storageSave();t=boot();step(2);assert(t.outfit.skin==='alien','skin lost '+JSON.stringify(t.outfit));assert(t.validOutfit({skin:'nope'}).skin==='','bad skin not dropped');});
check('players: fresh boot has an id but no name yet, and no modal before the delay',()=>{store.delete('gas-player-v1');t=boot();step(2);assert(t.player.id&&!t.player.name,JSON.stringify(t.player));assert(doc.getElementById('modalTitle').textContent==='','modal open before the delay');});
check('players: name rules',()=>{assert(!t.cleanName('ab').ok);assert(!t.cleanName('fuckface').ok);const r=t.cleanName('  Pixel Fox 42!! ');assert(r.ok&&r.name==='Pixel Fox 42',JSON.stringify(r));assert(t.setPlayerName('GabeTheGreat').ok);assert(t.player.name==='GabeTheGreat');assert(JSON.parse(store.get('gas-player-v1')).name==='GabeTheGreat');assert(byId.get('player').textContent==='👤 GabeTheGreat',byId.get('player').textContent);});
check('leaderboard: local-only mode shows this device scores',()=>{t.LB.url='';t.LB.apiKey='';assert(t.openLeaderboard('brawl'));assert(/Monster Brawl/.test(byId.get('modalTitle').textContent));t.closeModal();assert(!t.openLeaderboard('nope'));});
check('leaderboard: scores upload as PUT and the top 10 renders with me highlighted',()=>{const calls=[];t.LB.url='https://example-rtdb.firebaseio.com';t.setFetch((url,o)=>{calls.push({url,o});if(o&&o.method==='PUT')return Promise.resolve({ok:true,json:()=>Promise.resolve({})});return Promise.resolve({ok:true,json:()=>Promise.resolve({a1:{name:'Zed',score:50},[t.player.id]:{name:'GabeTheGreat',score:120},b2:{name:'Amy',score:90},bad:{name:5,score:'x'}})});});assert(t.lbReport('brawl',120));assert(!t.lbReport('brawl',100),'worse score reported');return Promise.resolve().then(()=>t.lbFlush()).then(()=>{const put=calls.find(c=>c.o&&c.o.method==='PUT'&&c.url.indexOf('/scores/brawl/')>0);assert(put,'no brawl PUT in '+calls.map(c=>c.url).join(','));assert(put.url.indexOf('/scores/brawl/'+t.player.id+'.json')>0,put.url);const body=JSON.parse(put.o.body);assert(body.name==='GabeTheGreat'&&body.score===120&&body.at&&body.at['.sv']==='timestamp',put.o.body);assert(t.lbQueue.length===0,'queue not drained');return t.lbTop('brawl');}).then(rows=>{assert(rows.length===3&&rows[0].name==='GabeTheGreat'&&rows[2].name==='Zed',JSON.stringify(rows));assert(t.lbCache.brawl.rows.length===3);const g=calls.find(c=>!c.o||!c.o.method);assert(/orderBy="score"&limitToLast=10/.test(g.url),g.url);});});
check('leaderboard: offline keeps the queue and shows the cached top 10',()=>{t.setOnline(false);assert(t.lbReport('hoops',31));assert(t.lbQueue.some(q=>q.key==='hoops'),'not queued');t.openLeaderboard('brawl');const txt=JSON.stringify(byId.get('modalBody').children.map(c=>c.textContent||c.children.map(x=>x.textContent).join('|')));assert(/offline/.test(txt),txt);t.closeModal();t.setOnline(true);t.setFetch(()=>Promise.reject(new Error('down')));t.openLeaderboard('hoops');t.closeModal();});
check('leaderboard: House Hunt is lower-is-better and uses limitToFirst',()=>{delete t.lbLocal.house;assert(t.lbReport('house',95));assert(t.lbReport('house',80),'faster time should count');assert(!t.lbReport('house',90),'slower time counted');const calls=[];t.setFetch(url=>{calls.push(url);return Promise.resolve({ok:true,json:()=>Promise.resolve({})});});return t.lbTop('house').then(()=>{assert(/limitToFirst=10/.test(calls[0]),calls[0]);});});
check('leaderboard: finishing Monster Brawl reports its score',()=>{t.startModGame(t.BRAWL,{});const A=t.game.arena;A.score=777;t.finishMod(t.game,true,'x','y');assert(t.lbQueue.some(q=>q.key==='brawl'&&q.score===777)||t.lbCache,'brawl not queued');t.backToDrawing();t.LB.url='';});
check('leaderboard auth: anonymous sign-up, token reuse, refresh, and uid in the write path',()=>{t.LB.url='https://example-rtdb.firebaseio.com';t.LB.apiKey='KEY123';t.setAuthState(null);const calls=[];t.setFetch((url,o)=>{calls.push({url,o});if(url.indexOf('accounts:signUp')>0)return Promise.resolve({ok:true,json:()=>Promise.resolve({localId:'uidABC',idToken:'tok1',refreshToken:'ref1',expiresIn:'3600'})});if(url.indexOf('securetoken')>0)return Promise.resolve({ok:true,json:()=>Promise.resolve({user_id:'uidABC',id_token:'tok2',refresh_token:'ref2',expires_in:'3600'})});return Promise.resolve({ok:true,json:()=>Promise.resolve({})});});return t.lbAuth().then(tok=>{assert(tok==='tok1',tok);assert(t.lbUid()==='uidABC');assert(JSON.parse(store.get('gas-lb-auth-v1')).uid==='uidABC');return t.lbAuth();}).then(tok=>{assert(tok==='tok1','should reuse the cached token');assert(calls.length===1,'extra auth calls '+calls.length);t.lbAuthState.exp=Date.now()-1;return t.lbAuth();}).then(tok=>{assert(tok==='tok2','refresh did not run');delete t.lbLocal.plane;assert(t.lbReport('plane',55));return t.lbFlush();}).then(()=>{const put=calls.find(c=>c.o&&c.o.method==='PUT'&&c.url.indexOf('/scores/plane/')>0);assert(put,'no plane PUT');assert(put.url.indexOf('/scores/plane/uidABC.json?auth=tok2')>0,put.url);});});
check('leaderboard auth: a dead refresh token falls back to a fresh anonymous sign-up',()=>{const calls=[];t.setFetch((url,o)=>{calls.push(url);if(url.indexOf('securetoken')>0)return Promise.resolve({ok:false,status:400,json:()=>Promise.resolve({})});if(url.indexOf('accounts:signUp')>0)return Promise.resolve({ok:true,json:()=>Promise.resolve({localId:'uidNEW',idToken:'tok9',refreshToken:'ref9',expiresIn:'3600'})});return Promise.resolve({ok:true,json:()=>Promise.resolve({})});});t.lbAuthState.exp=0;return t.lbAuth().then(tok=>{assert(tok==='tok9'&&t.lbUid()==='uidNEW',tok+' '+t.lbUid());t.LB.url='';t.LB.apiKey='';t.setAuthState(null);});});
check('scenes still fine after everything',()=>{for(let i=0;i<t.SCENES.length;i++){t.setBackground(i);step(1);}});
runChecks().then(()=>{console.log('\n'+passed+' passed, '+failed+' failed');if(failed){console.log('\n'+fails.join('\n\n'));process.exit(1);}process.exit(0);});
