// Headless logic checks for Gabriel's Animation Studio.
// Run: node test/run.js   (needs Node 18+; no packages)
const fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(process.env.GAS_ROOT||path.join(__dirname,'..'),'index.html'),'utf8');
let script=html.match(/<script>([\s\S]*)<\/script>/)[1];
const HOOK=`window.__t={get strokes(){return strokes},setStrokes(l){strokes=l;nextId=Math.max(0,...l.map(s=>s.id))+1;rig=null;history=[];dirty=true;},get rig(){return rig},get game(){return game},get outfit(){return outfit},setOutfit(o){outfit=o;},get morph(){return morph},setMorph,get morphT(){return morphT},startAnimation,stopAnimation,startGame,startModGame,backToDrawing,jump,held,inputDown,inputUp,inp,FIGHT,BRAWL,QUEST,HOUSE,BOTS,makeBot,botStrokes,snapshotHero,loadHero,get heroes(){return heroes},buildCharacter,currentCharacter,drawCharacterThumb,serializeChar,validChar,scene,SCENES,setBackground(i){background=i;},get background(){return background},openScenePicker,openHeroes,openVsSetup,openQuestMap,openOnline,closeModal,storageSave,load,get progress(){return progress},genLevel,WORLDS,ensureRig,netGuestUpdate,NET,finishMod,poseFor,fightOptions,get animation(){return animation},get heroName(){return heroName}};`;
if(!script.includes('/* TEST_HOOK */'))throw new Error('TEST_HOOK marker missing');
script=script.replace('/* TEST_HOOK */',HOOK);
// ---- fake DOM ----
function makeCtx(){const t={globalAlpha:1,lineWidth:1,font:'',textAlign:'',textBaseline:'',fillStyle:'',strokeStyle:'',lineCap:'',lineJoin:''};return new Proxy(t,{get(o,k){if(k in o)return o[k];if(k==='createLinearGradient'||k==='createRadialGradient')return()=>({addColorStop(){}});if(k==='measureText')return()=>({width:10});if(k==='getImageData')return()=>({data:new Uint8ClampedArray(4)});return()=>undefined;},set(o,k,v){o[k]=v;return true;}});}
class El{constructor(tag,id){this.tag=tag;this.id=id||'';this.textContent='';this.hidden=false;this.disabled=false;this.className='';this.children=[];this.attrs={};this.dataset={};this.style={setProperty(){}};this.value='';this.width=300;this.height=150;const cls=new Set();this.classList={add:c=>cls.add(c),remove:c=>cls.delete(c),toggle:(c,f)=>{f===undefined?(cls.has(c)?cls.delete(c):cls.add(c)):(f?cls.add(c):cls.delete(c));},contains:c=>cls.has(c)};this._ctx=null;}
getContext(){return this._ctx||(this._ctx=makeCtx());}
setAttribute(k,v){this.attrs[k]=String(v);}getAttribute(k){return this.attrs[k];}append(...n){this.children.push(...n);}
set innerHTML(v){this.children=[];}get innerHTML(){return '';}
querySelectorAll(sel){const out=[];const walk=n=>{for(const c of n.children||[]){if(!(c instanceof El))continue;if(sel==='button'&&c.tag==='button')out.push(c);walk(c);}};walk(this);return out;}
addEventListener(){}removeEventListener(){}focus(){}
getBoundingClientRect(){return{left:0,top:0,width:1280,height:720};}
setPointerCapture(){}releasePointerCapture(){}hasPointerCapture(){return false;}}
const byId=new Map();
const doc={hidden:false,body:new El('body'),head:new El('head'),modelContext:undefined,getElementById(id){if(!byId.has(id))byId.set(id,new El('div',id));return byId.get(id);},createElement(tag){return new El(tag);},querySelectorAll(){return[];},addEventListener(){},removeEventListener(){}};
byId.set('canvas',Object.assign(new El('canvas','canvas'),{width:1280,height:720}));
const store=new Map();const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
let rafCb=null;
const win={document:doc,localStorage,addEventListener(){},devicePixelRatio:1,requestAnimationFrame(cb){rafCb=cb;return 1;},setTimeout,clearTimeout,Date,Math,JSON,Number,String,Array,Object,Set,Map,Promise,Error,Uint8ClampedArray,console,performance:{now:()=>Date.now()},AbortController:class{constructor(){this.signal={}}abort(){}},isFinite,parseInt,parseFloat};
win.window=win;win.self=win;
function boot(){byId.clear();byId.set('canvas',Object.assign(new El('canvas','canvas'),{width:1280,height:720}));rafCb=null;const ctx=vm.createContext(win);vm.runInContext(script,ctx,{filename:'index.html'});return win.__t;}
let now=0;function step(n=1){for(let i=0;i<n;i++){now+=16.67;const cb=rafCb;rafCb=null;cb(now);if(!rafCb)throw new Error('frame did not re-register');}}
let passed=0,failed=0;const fails=[];
function check(name,fn){try{fn();passed++;console.log('  ok   '+name);}catch(e){failed++;fails.push(name+': '+(e&&e.stack||e));console.log('  FAIL '+name+' -> '+(e&&e.message||e));}}
function assert(c,msg){if(!c)throw new Error(msg||'assertion failed');}
// ---- tests ----
if(require.main!==module){module.exports={boot,step,byId,doc,store,check,assert};return;}
console.log('Booting game script...');
let t=boot();
const stick=(color='#e65345')=>t.botStrokes(color).map(s=>({...s,points:s.points.map(p=>({...p}))}));
check('boots and renders 5 frames',()=>{step(5);assert(t.game===null);});
check('rig inferred from a stick figure and Walk animates',()=>{t.setStrokes(stick());assert(t.startAnimation('Walk'));assert(t.rig,'rig missing');assert(t.rig.fit.scale>0);step(40);assert(t.animation==='Walk');t.stopAnimation();});
check('every movement animates',()=>{for(const m of ['Walk','Run','Jump','Dance','Wave','Kick','Flip','Cartwheel','Fly','Zombie']){assert(t.startAnimation(m));step(10);t.stopAnimation();}});
check('fight poses resolve for every fit',()=>{for(const n of ['Guard','Punch','Swing','Shoot','Block','Hurt','KO','Win','Fall','Sit']){const p=t.poseFor(n,.3,t.rig.fit);assert(p&&typeof p==='object');for(const k in p)assert(Number.isFinite(p[k]),n+'.'+k+' not finite');}});
check('outfits and morph paint without errors',()=>{for(const hat of ['','crown','wizard','cap','helmet','halo','party','horns'])for(const weapon of ['','sword','axe','hammer','wand','blaster','bow','shield']){t.setOutfit({hat,cape:['','red','rainbow','shadow'][hat.length%4],top:['','shirt','armor','super','robe','ninja','stripes'][weapon.length%7],weapon});t.startAnimation('Run');step(3);t.stopAnimation();}t.setMorph(true);step(80);assert(t.morphT===1,'morphT '+t.morphT);t.startAnimation('Dance');step(20);t.stopAnimation();t.setMorph(false);step(80);assert(t.morphT===0);});
check('all 18 scenes draw (normal and thumbnails)',()=>{for(let i=0;i<t.SCENES.length;i++){t.setBackground(i);t.scene(1.5,300);}t.openScenePicker();t.closeModal();t.setBackground(6);});
check('legacy games run with outfits on',()=>{t.setOutfit({hat:'crown',cape:'red',top:'super',weapon:'sword'});t.setMorph(true);for(const type of ['platform','dash','catch','flap','pop','dodge','bounce','goal']){assert(t.startGame(type),type);for(let i=0;i<240;i++){if(i%40===0)t.held.right.add('k');if(i%40===25)t.held.right.delete('k');if(i%30===0)t.jump();step(1);}t.backToDrawing();}});
check('hero library: save, build, thumbnail, load',()=>{const h=t.snapshotHero('Test Hero');assert(h&&h.name==='Test Hero');assert(t.heroes.length===1);const ch=t.buildCharacter(h);assert(ch.rig.bindings.size===h.strokes.length);const c=doc.createElement('canvas');c.width=c.height=140;t.drawCharacterThumb(c,ch);t.loadHero(h);assert(t.rig&&t.heroName==='Test Hero');t.openHeroes();t.closeModal();});
check('all four bots build',()=>{for(const b of t.BOTS){const ch=t.makeBot(b);assert(ch.rig.fit.headR>10,b.name+' head');assert(ch.rest.h>200,b.name+' height');}});
check('online hero payload round-trips',()=>{const me=t.currentCharacter();const s=JSON.parse(JSON.stringify(t.serializeChar(me)));assert(t.validChar(s));const back=t.buildCharacter(s);assert(back.strokes.length===s.strokes.length);});
function randomInputs(pl,i){const acts=['left','right','up','a','b','c'];if(i%7===0){for(const a of acts)t.inputUp(pl,a,'t');t.inputDown(pl,acts[(i/7|0)%acts.length],'t');}}
check('VS Computer fight finishes with a result (hard bot, weapons)',()=>{const me=t.currentCharacter();const bot=t.makeBot(t.BOTS[0]);assert(t.startModGame(t.FIGHT,{p1:me,p2:bot,cpu:'hard'}));let i=0;while(!t.game.over&&i<60*200){randomInputs('p1',i);step(1);i++;}assert(t.game.over,'fight never ended');assert(byId.get('resultTitle').textContent.length>0);t.backToDrawing();});
check('2-player fight, all bots, finishes',()=>{const a=t.makeBot(t.BOTS[1]),b=t.makeBot(t.BOTS[3]);assert(t.startModGame(t.FIGHT,{p1:a,p2:b}));assert(t.game.duo===true);let i=0;while(!t.game.over&&i<60*200){randomInputs('p1',i);randomInputs('p2',i+3);step(1);i++;}assert(t.game.over,'2p fight never ended');t.backToDrawing();});
check('round timer runs out gives a decision',()=>{const a=t.makeBot(t.BOTS[2]),b=t.makeBot(t.BOTS[2]);t.startModGame(t.FIGHT,{p1:a,p2:b});let i=0;while(!t.game.over&&i<60*230){step(1);i++;}assert(t.game.over,'idle fight never ended');t.backToDrawing();});
check('Monster Brawl: a scripted player beats wave 1 slimes by punching',()=>{assert(t.startModGame(t.BRAWL,{}));let i=0;while(!t.game.over&&i<60*60){const A=t.game.arena,f=A.player,e=A.enemies[0];if(A.wave>=2)break;if(e){const d=e.x-f.x;t.inputUp('p1','left','k');t.inputUp('p1','right','k');if(Math.abs(d)>90)t.inputDown('p1',d>0?'right':'left','k');else if(i%20===0)t.inputDown('p1','a','k');else t.inputUp('p1','a','k');}step(1);i++;}assert(t.game.arena.kills>=3,'kills '+t.game.arena.kills+' hp '+t.game.arena.player.hp);t.backToDrawing();});
check('Monster Brawl: all waves and the boss can be won',()=>{assert(t.startModGame(t.BRAWL,{}));let i=0,waves=new Set();while(!t.game.over&&i<60*120){const A=t.game.arena;waves.add(A.wave);A.player.hp=100;if(i%60===0)A.enemies.forEach(e=>{e.hp=0;});step(1);i++;}assert(t.game.over&&/Champion/.test(byId.get('resultTitle').textContent),'waves '+[...waves]+' title '+byId.get('resultTitle').textContent);t.backToDrawing();});
check('Monster Brawl loss path',()=>{t.startModGame(t.BRAWL,{});t.game.arena.player.hp=1;let i=0;while(!t.game.over&&i<60*60){step(1);i++;}assert(t.game.over);assert(/wave/i.test(byId.get('resultText').textContent));t.backToDrawing();});
check('Space Quest: every world generates and runs',()=>{for(let w=0;w<t.WORLDS.length;w++){const L=t.genLevel(t.WORLDS[w]);assert(L.cells.length===5&&L.segs.length>0,'world '+w);assert(t.startModGame(t.QUEST,{world:w}));for(let i=0;i<400&&!t.game.over;i++){randomInputs('p1',i);step(1);}t.backToDrawing();}});
check('Space Quest: chain Earth to the Sun by reaching each rocket',()=>{t.progress.quest.unlocked=1;assert(t.startModGame(t.QUEST,{world:0}));let guard=0;while(!t.game.over&&guard<60*60*5){const q=t.game.q;if(q.phase==='play'){q.p.x=q.level.goal;q.p.y=640;}step(1);guard++;}assert(t.game.over,'never finished');assert(/Sun/.test(byId.get('resultTitle').textContent),byId.get('resultTitle').textContent);assert(t.progress.quest.unlocked===t.WORLDS.length,'unlocked '+t.progress.quest.unlocked);t.openQuestMap();t.closeModal();t.backToDrawing();});
check('Space Quest: falling into pits three times ends the level',()=>{t.startModGame(t.QUEST,{world:2});const q=t.game.q;q.level.segs=[];q.level.plats=[];let i=0;while(!t.game.over&&i<60*30){q.p.inv=0;step(1);i++;}assert(t.game.over,'hearts '+t.game.hearts);assert(/try/i.test(byId.get('resultTitle').textContent));t.backToDrawing();});
check('House Hunt: walk every room and find all 8 things',()=>{assert(t.startModGame(t.HOUSE,{}));const h=t.game.h;const visited=new Set();const go=(room,x)=>{h.room=room;h.p.x=x;};const items=[['living',600],['kitchen',560],['bedroom',520],['bathroom',380],['yard',1000],['garage',980],['basement',1000],['playroom',700]];for(const [room,x] of items){go(room,x);visited.add(room);step(2);}assert(t.game.over,'not finished, found '+h.found.size);assert(/found everything/i.test(byId.get('resultTitle').textContent));t.backToDrawing();
t.startModGame(t.HOUSE,{});const H2=t.game.h;H2.p.x=20;t.inputDown('p1','left','k');step(2);assert(H2.room==='garage','door left -> '+H2.room);t.inputUp('p1','left','k');H2.p.x=1270;t.inputDown('p1','right','k');step(3);assert(H2.room==='living','door right -> '+H2.room);t.inputUp('p1','right','k');H2.p.x=1090;t.inputDown('p1','up','k');step(1);t.inputUp('p1','up','k');assert(H2.room==='bedroom','stairs up -> '+H2.room);t.inputDown('p1','down','k');step(1);t.inputUp('p1','down','k');assert(H2.room==='living','stairs down -> '+H2.room);t.backToDrawing();});
check('save + reload keeps outfit, morph, heroes and progress',()=>{t.setOutfit({hat:'halo',cape:'gold',top:'ninja',weapon:'bow'});t.setMorph(true);t.storageSave();const saved=JSON.parse(store.get('doodle-go-v1'));assert(saved.outfit.hat==='halo'&&saved.morph===true);t=boot();step(2);assert(t.outfit.hat==='halo'&&t.outfit.weapon==='bow',JSON.stringify(t.outfit));assert(t.morph===true&&t.morphT===1);assert(t.heroes.length===1);assert(t.progress.quest.unlocked===t.WORLDS.length);assert(t.rig,'rig restored');});
check('VS setup modal builds with current drawing, heroes and bots',()=>{const opts=t.fightOptions();assert(opts.length===1+1+4,'options '+opts.length);t.openVsSetup(true);t.closeModal();t.openVsSetup(false);t.closeModal();t.openOnline();t.closeModal();});
check('guest fight applies host snapshots',()=>{const me=t.currentCharacter(),bot=t.makeBot(t.BOTS[2]);t.startModGame(t.FIGHT,{p1:bot,p2:me,online:{role:'guest'}});t.NET.role='guest';t.NET.state={t:'st',ph:'fight',pt:1,rd:1,tm:50,f:[{x:400,y:640,vx:0,vy:0,fc:1,st:'punch',t:.1,hp:80,w:0,g:true,an:1},{x:700,y:640,vx:0,vy:0,fc:-1,st:'hurt',t:.1,hp:60,w:1,g:true,an:1}],sh:[{x:500,y:500,vx:600,type:'wand'}],ev:[{k:'hit',x:600,y:500}]};step(3);const A=t.game.arena;assert(A.fighters[0].hp===80&&A.fighters[1].hp===60&&A.phase==='fight');t.NET.role=null;t.backToDrawing();});
check('scenes still fine after everything',()=>{for(let i=0;i<t.SCENES.length;i++){t.setBackground(i);step(1);}});
console.log('\n'+passed+' passed, '+failed+' failed');
if(failed){console.log('\n'+fails.join('\n\n'));process.exit(1);}
